name: cicd

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        type: choice
        default: "development"
        options:
          - "development"

      force_deploy:
        description: "Force deployment even if no changes detected"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        # backend
      - run: bun install --frozen-lockfile
        working-directory: ./apps/backend/
      - run: bun test
        working-directory: ./apps/backend/
      - run: bun run build
        working-directory: ./apps/backend/
        # frontend
      - run: bun install --frozen-lockfile
        working-directory: ./apps/frontend/
      - run: bun test
        working-directory: ./apps/frontend/
      - run: bun run build
        working-directory: ./apps/frontend/
        # deploy
      - name: prepare build
        if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy)
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")
          sed -i'' -e "s/{{VERSION}}/$SHA_SHORT/" ./apps/frontend/dist/index.html
          sed -i'' -e "s/{{BUILD_TIME}}/$BUILD_TIME/" ./apps/frontend/dist/index.html
      - name: Upload build-artifacts
        if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifacts
          path: |
            ./apps/frontend/dist/

  trigger-deploy-backend:
    needs: build
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy)
    uses: ./.github/workflows/deploy_backend.yml
    secrets: inherit

  trigger-deploy-frontend:
    needs: trigger-deploy-backend
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy)
    uses: ./.github/workflows/deploy_frontend.yml
    secrets: inherit
